server.port=8094
server.servlet.context-path=/decision
spring.application.name=decision

app.ml.base-url=http://ml-python:8000
app.integration.base-url=http://integration:8095/integration

app.decision.weather-weight=0.50
app.decision.market-weight=0.25
app.decision.ndvi-weight=0.25
app.decision.high-threshold=0.65
app.decision.medium-threshold=0.40

management.endpoints.web.exposure.include=health,info,metrics
