server.port=8094
server.servlet.context-path=/decision
spring.application.name=decision

app.ml.base-url=http://localhost:8000
app.integration.base-url=http://localhost:8095/integration

management.endpoints.web.exposure.include=health,info,metrics
