server.port=8095
server.servlet.context-path=/integration
spring.application.name=integration

app.integration.cache-ttl-seconds=300
app.integration.weather-external-enabled=true
app.integration.market-external-enabled=true
app.integration.ndvi-external-enabled=true
app.integration.weather-api-base-url=https://api.open-meteo.com/v1/forecast
app.integration.market-api-base-url=https://api.worldbank.org/v2/country

management.endpoints.web.exposure.include=health,info,metrics
