spring.application.name=eureka-server
server.port=8090

eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=false
eureka.server.enableSelfPreservation=true

eureka.client.service-url.defaultZone=http://discovery-server:8090/eureka/
eureka.client.register-with-eureka=false
spring.cloud.config.uri=http://config-server:8888

# mvn clean package -Dspring.profiles.active=docker -DskipTests