spring.application.name=configServer
server.port=8888

eureka.client.service-url.defaultZone=http://localhost:8090/eureka/
spring.cloud.config.server.native.search-locations=${CONFIG_REPO_LOCATION:file:../../config-repo,file:../config-repo,file:./config-repo}
management.endpoints.web.exposure.include=*

## mvn spring-boot:run -Dspring-boot.run.profiles=docker
